import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.Topology.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic

open MeasureTheory
open Set
open BorelSpace MeasurableSpace

/-- The main theorem: The σ-algebra generated by the preimage of a random variable
    under open sets is the same as the σ-algebra generated by the preimage of the random variable
    under all Borel sets. -/
theorem preimage_open_sigma_eq_preimage_borel_sigma {X Y : Type*} [MeasurableSpace X]
  [TopologicalSpace Y] [MeasurableSpace Y] [BorelSpace Y] (f : X → Y) :
  MeasurableSpace.generateFrom (preimage f '' { U : Set Y | IsOpen U }) = MeasurableSpace.comap f (borel Y) := by
  rw [← MeasurableSpace.comap_generateFrom]
  congr
